### ISSUE TITLE
Stops working after package upgrade

### ISSUE THREAD

**Issue by worikgh** [rksm/emacs-rust-config#10]
Emacs: 30.0.50
Running on a Raspberry Pi 4
Upgraded all packages

Now I get errors when I try toload rust files
```
Error (use-package): Cannot load flycheck 
Error (use-package): Cannot load dap-mode
```

```
cd /tmp
cargo new test_issue
emacs -nw -q --load ~/emacs-rust-config/standalone.el /tmp/test_issue/src/main.rs
```

**Comment by worikgh** [comment]
Looking into the `*Messages` buffer I installed packages:
`dash` and
`lsp-treemacs`

and the errors have gone away

**Comment by getong** [comment]
I have the same error after upgraded, my error msg is :
```
File mode specification error: (void-function rust-ts-mode)
```
I think this might be a error with lsp.

**Comment by getong** [comment]
I made a issue, emacs-lsp/lsp-mode#3882
which address this problem.
