### ISSUE TITLE
Link in README is dead

### ISSUE THREAD

**Issue by jamiebill** [rksm/emacs-rust-config#15]
The link in the README isn't working. I came across the link to your Github from the Rust forum, and was excited to read the blog when I saw it, as I'm getting my Emacs set up for Rust stuff and every little helps. No worries if you've taken the blog down or something, of course, but I thought you'd like to know if you haven't noticed.

**Comment by rksm** [comment]
Thanks for letting me know. I changed the URL server side but not here. Should be fixed now.
