### ISSUE TITLE
Emacs freezing when saving rs file

### ISSUE THREAD

**Issue by antonymerle** [rksm/emacs-rust-config#6]
Hi, thanks a lot for the config !

Everything seemed to work well except when I try to save a rust file, emacs freezes and I need eventually to kill the process and restart. The modifications on the file are saved when I reopen it.

I am on windows 10, I use clang/LLVM and the last rust-analyzer version.

Does anyone have encountered the same problem ?

**Comment by rksm** [comment]
Hi @waldganger, I haven't seen this happen yet, but it might be related to the pretty printing as this is what is happening when saving. I recently made a [change](https://github.com/rksm/emacs-rust-config/commit/7f672f9875df2851327f446495ca7b683ef18eac) to the config as a workaround of https://github.com/brotzeit/rustic/issues/253. Not sure if this is related but maybe it makes a difference.

If not, try to disable the pretty printing and see if this helps.
